FROM mariadb:latest
CMD ["mysqld"]
EXPOSE 3306

# docker/database/Dockerfile
#FROM postgres:latest
#ENV POSTGRES_USER <your user>
#ENV POSTGRES_PASSWORD <your password>
#EXPOSE 3306
#RUN apk add --no-cache bash